FROM ubuntu:bionic
RUN apt-get update
RUN apt-get install -y build-essential software-properties-common
RUN apt-get update
RUN add-apt-repository ppa:webupd8team/java && apt-get update
RUN echo "oracle-java8-installer shared/accepted-oracle-license-v1-1 select true" | debconf-set-selections
RUN echo "oracle-java8-installer shared/accepted-oracle-license-v1-1 seen true" | debconf-set-selections
RUN apt-get update
RUN apt-get install -y oracle-java8-installer maven \
    python3-dev python3-pip python3-virtualenv \
    libsasl2-dev libldap2-dev libssl-dev \
    nodejs
RUN apt-get install -y npm
RUN npm install avrodoc -g
ENV PYTHONUNBUFFERED 1
RUN mkdir /gel
RUN mkdir /gel/GelReportModels
WORKDIR /gel
ADD . /gel/GelReportModels
ADD m2_settings.xml /gel
RUN mkdir -p ~/.m2 && cp m2_settings.xml ~/.m2/settings.xml
WORKDIR /gel/GelReportModels
RUN pip3 install --upgrade pip==18.0
ENV GEL_REPORT_MODELS_PYTHON_VERSION 3
RUN pip3 install .